export const COUNT_INCREASE = "COUNT_INCREASE";
export const COUNT_DECREASE = "COUNT_DECREASE";
export const COUNT_RESET = "COUNT_RESET";
export const COUNT_INCREASE_BY_FIVE = "COUNT_INCREASE_BY_FIVE";
export const COUNT_DECREASE_BY_FIVE = "COUNT_DECREASE_BY_FIVE";
export const CHANGE_COUNT = "CHANGE_COUNT";
export const RESET_COUNT = "RESET_COUNT";
